import { FoodItem } from './supabase/client';

/**
 * Restaurant menu items - Tim Hortons, Starbucks, McDonald's, Wendy's
 * All nutritional values are per 100g for consistency
 */

export const RESTAURANT_FOODS: Omit<FoodItem, 'id' | 'tenantid' | 'projectid' | 'created_at' | 'updated_at'>[] = [
  // ============================================
  // TIM HORTONS
  // ============================================
  {
    name: 'Breakfast Sandwich - Egg & Cheese on English Muffin',
    brand: 'Tim Hortons',
    category: 'breakfast',
    description: 'Egg and cheese breakfast sandwich on English muffin',
    calories_per_100g: 214,
    protein_per_100g: 11.4,
    carbs_per_100g: 24.3,
    fat_per_100g: 7.1,
    fiber_per_100g: 1.4,
    sugar_per_100g: 2.9,
    sodium_per_100g: 571,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'sandwich', amount: 1, grams: 140, label: '1 sandwich (140g)' },
    ],
    default_serving_size: { unit: 'sandwich', amount: 1, grams: 140, label: '1 sandwich (140g)' },
    bloom_score: 72,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Tim Hortons Nutrition',
  },
  {
    name: 'Bagel - Plain',
    brand: 'Tim Hortons',
    category: 'breakfast',
    description: 'Plain bagel',
    calories_per_100g: 262,
    protein_per_100g: 9.5,
    carbs_per_100g: 52.4,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.4,
    sugar_per_100g: 4.8,
    sodium_per_100g: 457,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'bagel', amount: 1, grams: 105, label: '1 bagel (105g)' },
    ],
    default_serving_size: { unit: 'bagel', amount: 1, grams: 105, label: '1 bagel (105g)' },
    bloom_score: 68,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Tim Hortons Nutrition',
  },
  {
    name: 'TimBit - Honey Dip',
    brand: 'Tim Hortons',
    category: 'snacks',
    description: 'Honey dip donut hole',
    calories_per_100g: 393,
    protein_per_100g: 5.4,
    carbs_per_100g: 53.6,
    fat_per_100g: 17.9,
    fiber_per_100g: 1.8,
    sugar_per_100g: 23.2,
    sodium_per_100g: 357,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'piece', amount: 1, grams: 14, label: '1 TimBit (14g)' },
      { unit: 'piece', amount: 5, grams: 70, label: '5 TimBits (70g)' },
    ],
    default_serving_size: { unit: 'piece', amount: 1, grams: 14, label: '1 TimBit (14g)' },
    bloom_score: 42,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Tim Hortons Nutrition',
  },
  {
    name: 'Coffee - Double Double (Medium)',
    brand: 'Tim Hortons',
    category: 'beverages',
    description: 'Coffee with 2 cream and 2 sugar',
    calories_per_100g: 38,
    protein_per_100g: 0.5,
    carbs_per_100g: 6.2,
    fat_per_100g: 1.5,
    fiber_per_100g: 0,
    sugar_per_100g: 6.2,
    sodium_per_100g: 13,
    serving_sizes: [
      { unit: 'ml', amount: 100, grams: 100, label: '100ml' },
      { unit: 'cup', amount: 1, grams: 340, label: '1 medium (340ml)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 340, label: '1 medium (340ml)' },
    bloom_score: 55,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Tim Hortons Nutrition',
  },
  {
    name: 'Chili - Homestyle',
    brand: 'Tim Hortons',
    category: 'meals',
    description: 'Homestyle chili',
    calories_per_100g: 88,
    protein_per_100g: 7.1,
    carbs_per_100g: 9.7,
    fat_per_100g: 2.7,
    fiber_per_100g: 2.7,
    sugar_per_100g: 2.7,
    sodium_per_100g: 353,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 280, label: '1 cup (280g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 280, label: '1 cup (280g)' },
    bloom_score: 78,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Tim Hortons Nutrition',
  },

  // ============================================
  // STARBUCKS
  // ============================================
  {
    name: 'Bacon, Gouda & Egg Sandwich',
    brand: 'Starbucks',
    category: 'breakfast',
    description: 'Bacon, gouda cheese, and egg on an English muffin',
    calories_per_100g: 238,
    protein_per_100g: 12.7,
    carbs_per_100g: 19.0,
    fat_per_100g: 11.1,
    fiber_per_100g: 1.6,
    sugar_per_100g: 2.4,
    sodium_per_100g: 635,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'sandwich', amount: 1, grams: 126, label: '1 sandwich (126g)' },
    ],
    default_serving_size: { unit: 'sandwich', amount: 1, grams: 126, label: '1 sandwich (126g)' },
    bloom_score: 74,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Starbucks Nutrition',
  },
  {
    name: 'Grande Caffe Latte (2% Milk)',
    brand: 'Starbucks',
    category: 'beverages',
    description: 'Espresso with steamed 2% milk',
    calories_per_100g: 40,
    protein_per_100g: 2.7,
    carbs_per_100g: 4.0,
    fat_per_100g: 1.7,
    fiber_per_100g: 0,
    sugar_per_100g: 4.0,
    sodium_per_100g: 40,
    serving_sizes: [
      { unit: 'ml', amount: 100, grams: 100, label: '100ml' },
      { unit: 'cup', amount: 1, grams: 473, label: '1 grande (473ml)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 473, label: '1 grande (473ml)' },
    bloom_score: 68,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Starbucks Nutrition',
  },
  {
    name: 'Chocolate Chip Cookie',
    brand: 'Starbucks',
    category: 'snacks',
    description: 'Classic chocolate chip cookie',
    calories_per_100g: 500,
    protein_per_100g: 5.0,
    carbs_per_100g: 65.0,
    fat_per_100g: 25.0,
    fiber_per_100g: 2.0,
    sugar_per_100g: 35.0,
    sodium_per_100g: 350,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cookie', amount: 1, grams: 60, label: '1 cookie (60g)' },
    ],
    default_serving_size: { unit: 'cookie', amount: 1, grams: 60, label: '1 cookie (60g)' },
    bloom_score: 45,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Starbucks Nutrition',
  },
  {
    name: 'Protein Box - Eggs & Cheese',
    brand: 'Starbucks',
    category: 'meals',
    description: 'Hard-boiled eggs, cheese, multigrain bread, peanut butter, grapes',
    calories_per_100g: 173,
    protein_per_100g: 10.2,
    carbs_per_100g: 14.3,
    fat_per_100g: 8.2,
    fiber_per_100g: 2.0,
    sugar_per_100g: 6.1,
    sodium_per_100g: 306,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'box', amount: 1, grams: 196, label: '1 box (196g)' },
    ],
    default_serving_size: { unit: 'box', amount: 1, grams: 196, label: '1 box (196g)' },
    bloom_score: 82,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Starbucks Nutrition',
  },
  {
    name: 'Chicken & Quinoa Protein Bowl',
    brand: 'Starbucks',
    category: 'meals',
    description: 'Chicken, quinoa, vegetables, and dressing',
    calories_per_100g: 143,
    protein_per_100g: 10.7,
    carbs_per_100g: 13.6,
    fat_per_100g: 5.0,
    fiber_per_100g: 2.1,
    sugar_per_100g: 2.9,
    sodium_per_100g: 286,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'bowl', amount: 1, grams: 280, label: '1 bowl (280g)' },
    ],
    default_serving_size: { unit: 'bowl', amount: 1, grams: 280, label: '1 bowl (280g)' },
    bloom_score: 88,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Starbucks Nutrition',
  },

  // ============================================
  // MCDONALD'S
  // ============================================
  {
    name: 'Big Mac',
    brand: 'McDonalds',
    category: 'meals',
    description: 'Two beef patties, special sauce, lettuce, cheese, pickles, onions on sesame seed bun',
    calories_per_100g: 255,
    protein_per_100g: 12.7,
    carbs_per_100g: 20.6,
    fat_per_100g: 13.8,
    fiber_per_100g: 1.6,
    sugar_per_100g: 3.6,
    sodium_per_100g: 476,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'burger', amount: 1, grams: 215, label: '1 burger (215g)' },
    ],
    default_serving_size: { unit: 'burger', amount: 1, grams: 215, label: '1 burger (215g)' },
    bloom_score: 58,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'McDonalds Nutrition',
  },
  {
    name: 'Egg McMuffin',
    brand: 'McDonalds',
    category: 'breakfast',
    description: 'Egg, Canadian bacon, and cheese on English muffin',
    calories_per_100g: 235,
    protein_per_100g: 14.1,
    carbs_per_100g: 21.2,
    fat_per_100g: 9.4,
    fiber_per_100g: 1.8,
    sugar_per_100g: 2.4,
    sodium_per_100g: 565,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'sandwich', amount: 1, grams: 141, label: '1 sandwich (141g)' },
    ],
    default_serving_size: { unit: 'sandwich', amount: 1, grams: 141, label: '1 sandwich (141g)' },
    bloom_score: 76,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'McDonalds Nutrition',
  },
  {
    name: 'Medium French Fries',
    brand: 'McDonalds',
    category: 'sides',
    description: 'Crispy golden french fries',
    calories_per_100g: 323,
    protein_per_100g: 3.4,
    carbs_per_100g: 41.4,
    fat_per_100g: 15.5,
    fiber_per_100g: 3.4,
    sugar_per_100g: 0.3,
    sodium_per_100g: 214,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'serving', amount: 1, grams: 117, label: '1 medium (117g)' },
    ],
    default_serving_size: { unit: 'serving', amount: 1, grams: 117, label: '1 medium (117g)' },
    bloom_score: 52,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'McDonalds Nutrition',
  },
  {
    name: 'Chicken McNuggets (6 piece)',
    brand: 'McDonalds',
    category: 'meals',
    description: 'Breaded chicken nuggets',
    calories_per_100g: 295,
    protein_per_100g: 15.7,
    carbs_per_100g: 16.9,
    fat_per_100g: 17.7,
    fiber_per_100g: 1.2,
    sugar_per_100g: 0,
    sodium_per_100g: 602,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'piece', amount: 6, grams: 102, label: '6 pieces (102g)' },
      { unit: 'piece', amount: 10, grams: 170, label: '10 pieces (170g)' },
    ],
    default_serving_size: { unit: 'piece', amount: 6, grams: 102, label: '6 pieces (102g)' },
    bloom_score: 62,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'McDonalds Nutrition',
  },
  {
    name: 'Grilled Chicken Salad',
    brand: 'McDonalds',
    category: 'meals',
    description: 'Mixed greens with grilled chicken',
    calories_per_100g: 47,
    protein_per_100g: 6.7,
    carbs_per_100g: 3.3,
    fat_per_100g: 1.3,
    fiber_per_100g: 1.3,
    sugar_per_100g: 2.0,
    sodium_per_100g: 200,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'salad', amount: 1, grams: 300, label: '1 salad (300g)' },
    ],
    default_serving_size: { unit: 'salad', amount: 1, grams: 300, label: '1 salad (300g)' },
    bloom_score: 85,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'McDonalds Nutrition',
  },

  // ============================================
  // WENDY'S
  // ============================================
  {
    name: 'Daves Single',
    brand: 'Wendys',
    category: 'meals',
    description: 'Quarter pound beef patty, lettuce, tomato, pickles, onion, ketchup, mayo',
    calories_per_100g: 247,
    protein_per_100g: 12.8,
    carbs_per_100g: 17.4,
    fat_per_100g: 13.9,
    fiber_per_100g: 1.2,
    sugar_per_100g: 4.1,
    sodium_per_100g: 422,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'burger', amount: 1, grams: 249, label: '1 burger (249g)' },
    ],
    default_serving_size: { unit: 'burger', amount: 1, grams: 249, label: '1 burger (249g)' },
    bloom_score: 64,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Wendys Nutrition',
  },
  {
    name: 'Spicy Chicken Sandwich',
    brand: 'Wendys',
    category: 'meals',
    description: 'Spicy breaded chicken breast with lettuce, tomato, mayo',
    calories_per_100g: 220,
    protein_per_100g: 11.3,
    carbs_per_100g: 19.8,
    fat_per_100g: 10.2,
    fiber_per_100g: 1.1,
    sugar_per_100g: 2.8,
    sodium_per_100g: 565,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'sandwich', amount: 1, grams: 212, label: '1 sandwich (212g)' },
    ],
    default_serving_size: { unit: 'sandwich', amount: 1, grams: 212, label: '1 sandwich (212g)' },
    bloom_score: 66,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Wendys Nutrition',
  },
  {
    name: 'Apple Pecan Chicken Salad',
    brand: 'Wendys',
    category: 'meals',
    description: 'Grilled chicken, apples, pecans, blue cheese, pomegranate vinaigrette',
    calories_per_100g: 107,
    protein_per_100g: 7.1,
    carbs_per_100g: 7.9,
    fat_per_100g: 5.0,
    fiber_per_100g: 1.4,
    sugar_per_100g: 5.7,
    sodium_per_100g: 286,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'salad', amount: 1, grams: 350, label: '1 salad (350g)' },
    ],
    default_serving_size: { unit: 'salad', amount: 1, grams: 350, label: '1 salad (350g)' },
    bloom_score: 89,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Wendys Nutrition',
  },
  {
    name: 'Chili (Small)',
    brand: 'Wendys',
    category: 'meals',
    description: 'Beef chili with beans',
    calories_per_100g: 106,
    protein_per_100g: 8.2,
    carbs_per_100g: 10.6,
    fat_per_100g: 3.5,
    fiber_per_100g: 3.5,
    sugar_per_100g: 2.9,
    sodium_per_100g: 424,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 245, label: '1 small (245g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 245, label: '1 small (245g)' },
    bloom_score: 80,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Wendys Nutrition',
  },
  {
    name: 'Baked Potato - Plain',
    brand: 'Wendys',
    category: 'sides',
    description: 'Plain baked potato',
    calories_per_100g: 94,
    protein_per_100g: 2.5,
    carbs_per_100g: 21.6,
    fat_per_100g: 0,
    fiber_per_100g: 2.5,
    sugar_per_100g: 1.0,
    sodium_per_100g: 12,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'potato', amount: 1, grams: 284, label: '1 potato (284g)' },
    ],
    default_serving_size: { unit: 'potato', amount: 1, grams: 284, label: '1 potato (284g)' },
    bloom_score: 90,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Wendys Nutrition',
  },
  {
    name: 'Frosty - Chocolate (Small)',
    brand: 'Wendys',
    category: 'beverages',
    description: 'Chocolate frozen dairy dessert',
    calories_per_100g: 140,
    protein_per_100g: 3.2,
    carbs_per_100g: 22.4,
    fat_per_100g: 4.0,
    fiber_per_100g: 0,
    sugar_per_100g: 19.2,
    sodium_per_100g: 80,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 250, label: '1 small (250ml)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 250, label: '1 small (250ml)' },
    bloom_score: 50,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Wendys Nutrition',
  },
];
