import { FoodItem } from './supabase/client';
import { getCommonServingSizes } from './serving-conversions';

/**
 * Sample food database - resembling MyFitnessPal's structure
 * All nutritional values are per 100g for consistency
 */

export const SAMPLE_FOODS: Omit<FoodItem, 'id' | 'tenantid' | 'projectid' | 'created_at' | 'updated_at'>[] = [
  // PROTEINS
  {
    name: 'Chicken Breast, Grilled',
    brand: null,
    category: 'protein',
    description: 'Skinless, boneless chicken breast, grilled',
    calories_per_100g: 165,
    protein_per_100g: 31,
    carbs_per_100g: 0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 74,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'oz', amount: 4, grams: 113, label: '4 oz (113g)' },
      { unit: 'oz', amount: 6, grams: 170, label: '6 oz (170g)' },
      { unit: 'piece', amount: 1, grams: 150, label: '1 breast (150g)' },
    ],
    default_serving_size: { unit: 'oz', amount: 4, grams: 113, label: '4 oz (113g)' },
    bloom_score: 95,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Salmon, Atlantic',
    brand: null,
    category: 'protein',
    description: 'Atlantic salmon, cooked',
    calories_per_100g: 206,
    protein_per_100g: 22,
    carbs_per_100g: 0,
    fat_per_100g: 13,
    fiber_per_100g: 0,
    sugar_per_100g: 0,
    sodium_per_100g: 59,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'oz', amount: 4, grams: 113, label: '4 oz (113g)' },
      { unit: 'oz', amount: 6, grams: 170, label: '6 oz (170g)' },
      { unit: 'piece', amount: 1, grams: 140, label: '1 fillet (140g)' },
    ],
    default_serving_size: { unit: 'oz', amount: 4, grams: 113, label: '4 oz (113g)' },
    bloom_score: 98,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Greek Yogurt, Plain',
    brand: 'Fage',
    category: 'dairy',
    description: '0% fat Greek yogurt',
    calories_per_100g: 59,
    protein_per_100g: 10,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 0,
    sugar_per_100g: 3.2,
    sodium_per_100g: 36,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 240, label: '1 cup (240g)' },
      { unit: 'cup', amount: 0.5, grams: 120, label: '½ cup (120g)' },
      { unit: 'container', amount: 1, grams: 170, label: '1 container (170g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 240, label: '1 cup (240g)' },
    bloom_score: 92,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Product Label',
  },

  // GRAINS
  {
    name: 'Brown Rice, Cooked',
    brand: null,
    category: 'grains',
    description: 'Long grain brown rice, cooked',
    calories_per_100g: 111,
    protein_per_100g: 2.6,
    carbs_per_100g: 23,
    fat_per_100g: 0.9,
    fiber_per_100g: 1.8,
    sugar_per_100g: 0.4,
    sodium_per_100g: 5,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 195, label: '1 cup cooked (195g)' },
      { unit: 'cup', amount: 0.5, grams: 98, label: '½ cup cooked (98g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 0.5, grams: 98, label: '½ cup cooked (98g)' },
    bloom_score: 85,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Quinoa, Cooked',
    brand: null,
    category: 'grains',
    description: 'Quinoa, cooked',
    calories_per_100g: 120,
    protein_per_100g: 4.4,
    carbs_per_100g: 21,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.8,
    sugar_per_100g: 0.9,
    sodium_per_100g: 7,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 185, label: '1 cup cooked (185g)' },
      { unit: 'cup', amount: 0.5, grams: 93, label: '½ cup cooked (93g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 0.5, grams: 93, label: '½ cup cooked (93g)' },
    bloom_score: 90,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Oats, Rolled',
    brand: 'Quaker',
    category: 'grains',
    description: 'Old fashioned rolled oats, dry',
    calories_per_100g: 389,
    protein_per_100g: 16.9,
    carbs_per_100g: 66,
    fat_per_100g: 6.9,
    fiber_per_100g: 10.6,
    sugar_per_100g: 0,
    sodium_per_100g: 2,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 0.5, grams: 40, label: '½ cup dry (40g)' },
      { unit: 'cup', amount: 1, grams: 80, label: '1 cup dry (80g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 0.5, grams: 40, label: '½ cup dry (40g)' },
    bloom_score: 88,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'Product Label',
  },

  // VEGETABLES
  {
    name: 'Broccoli, Cooked',
    brand: null,
    category: 'vegetables',
    description: 'Broccoli florets, steamed',
    calories_per_100g: 35,
    protein_per_100g: 2.4,
    carbs_per_100g: 7,
    fat_per_100g: 0.4,
    fiber_per_100g: 3.3,
    sugar_per_100g: 1.4,
    sodium_per_100g: 41,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 155, label: '1 cup (155g)' },
      { unit: 'cup', amount: 0.5, grams: 78, label: '½ cup (78g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 155, label: '1 cup (155g)' },
    bloom_score: 96,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Sweet Potato, Baked',
    brand: null,
    category: 'vegetables',
    description: 'Sweet potato, baked with skin',
    calories_per_100g: 90,
    protein_per_100g: 2,
    carbs_per_100g: 21,
    fat_per_100g: 0.2,
    fiber_per_100g: 3.3,
    sugar_per_100g: 6.5,
    sodium_per_100g: 36,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'piece', amount: 1, grams: 130, label: '1 medium (130g)' },
      { unit: 'cup', amount: 1, grams: 200, label: '1 cup cubed (200g)' },
    ],
    default_serving_size: { unit: 'piece', amount: 1, grams: 130, label: '1 medium (130g)' },
    bloom_score: 93,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Spinach, Raw',
    brand: null,
    category: 'vegetables',
    description: 'Baby spinach, fresh',
    calories_per_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.2,
    sugar_per_100g: 0.4,
    sodium_per_100g: 79,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 30, label: '1 cup (30g)' },
      { unit: 'cup', amount: 2, grams: 60, label: '2 cups (60g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 2, grams: 60, label: '2 cups (60g)' },
    bloom_score: 98,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },

  // FRUITS
  {
    name: 'Banana',
    brand: null,
    category: 'fruits',
    description: 'Fresh banana, raw',
    calories_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 23,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
    sugar_per_100g: 12,
    sodium_per_100g: 1,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'piece', amount: 1, grams: 118, label: '1 medium (118g)' },
      { unit: 'piece', amount: 1, grams: 150, label: '1 large (150g)' },
    ],
    default_serving_size: { unit: 'piece', amount: 1, grams: 118, label: '1 medium (118g)' },
    bloom_score: 85,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
  {
    name: 'Blueberries, Fresh',
    brand: null,
    category: 'fruits',
    description: 'Fresh blueberries',
    calories_per_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.4,
    sugar_per_100g: 10,
    sodium_per_100g: 1,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'cup', amount: 1, grams: 148, label: '1 cup (148g)' },
      { unit: 'cup', amount: 0.5, grams: 74, label: '½ cup (74g)' },
    ],
    default_serving_size: { unit: 'cup', amount: 1, grams: 148, label: '1 cup (148g)' },
    bloom_score: 94,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },

  // NUTS & SEEDS
  {
    name: 'Almonds',
    brand: null,
    category: 'nuts',
    description: 'Raw almonds',
    calories_per_100g: 579,
    protein_per_100g: 21,
    carbs_per_100g: 22,
    fat_per_100g: 50,
    fiber_per_100g: 12.5,
    sugar_per_100g: 4.4,
    sodium_per_100g: 1,
    serving_sizes: [
      { unit: 'g', amount: 100, grams: 100, label: '100g' },
      { unit: 'oz', amount: 1, grams: 28, label: '1 oz (28g)' },
      { unit: 'piece', amount: 23, grams: 28, label: '23 almonds (28g)' },
    ],
    default_serving_size: { unit: 'oz', amount: 1, grams: 28, label: '1 oz (28g)' },
    bloom_score: 87,
    is_custom: false,
    added_by: null,
    verified: true,
    source: 'USDA',
  },
];
